# Generated by Django 6.0.5 on 2026-05-14 16:23
"""Initial migrations for the resumes app."""

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(blank=True, max_length=160)),
                ("title", models.CharField(blank=True, max_length=160)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("current_role", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "experience",
                "verbose_name_plural": "experience",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_key", models.CharField(max_length=64, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=140)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("linkedin_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                ("professional_summary", models.TextField(blank=True)),
                (
                    "chosen_theme",
                    models.CharField(
                        choices=[("classic", "Classic"), ("modern", "Modern"), ("minimal", "Minimal")],
                        default="classic",
                        max_length=20,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        choices=[
                            ("slate", "Slate"),
                            ("blue", "Blue"),
                            ("emerald", "Emerald"),
                            ("rose", "Rose"),
                            ("amber", "Amber"),
                            ("violet", "Violet"),
                            ("cyan", "Cyan"),
                            ("stone", "Stone"),
                        ],
                        default="blue",
                        max_length=20,
                    ),
                ),
                (
                    "font_pairing",
                    models.CharField(
                        choices=[
                            ("serif", "Serif"),
                            ("sans", "Sans"),
                            ("editorial", "Editorial"),
                            ("compact", "Compact"),
                        ],
                        default="sans",
                        max_length=20,
                    ),
                ),
                ("jd_text", models.TextField(blank=True)),
                ("first_visit_notice_seen", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="resumes.experience",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="experience",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="experiences", to="resumes.profile"
            ),
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("institution", models.CharField(blank=True, max_length=160)),
                ("degree", models.CharField(blank=True, max_length=160)),
                ("field", models.CharField(blank=True, max_length=160)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("gpa", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="education", to="resumes.profile"
                    ),
                ),
            ],
            options={
                "verbose_name": "education",
                "verbose_name_plural": "education",
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=160)),
                ("issuing_body", models.CharField(blank=True, max_length=160)),
                ("date_earned", models.DateField(blank=True, null=True)),
                ("expiry", models.DateField(blank=True, null=True)),
                ("credential_id", models.CharField(blank=True, max_length=120)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="resumes.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[("technical", "Technical"), ("language", "Language"), ("soft", "Soft")],
                        default="technical",
                        max_length=20,
                    ),
                ),
                (
                    "proficiency",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="skills", to="resumes.profile"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "abstract": False,
            },
        ),
    ]
