"""Tests for the analysis services for the resumes app."""

from __future__ import annotations

import pytest

from resumes.models import Achievement, Certification, Profile
from resumes.services.analysis import (
    action_verb_suggestions,
    analyze_job_description,
    check_bullet_quality,
    completeness_score,
    extract_keywords,
    keyword_present_in_resume,
    profile_resume_text,
    replace_weak_opener,
    tokenize_for_matching,
)


def test_bullet_warnings_cover_all_codes():
    weak = check_bullet_quality("Responsible for reports")
    long_text = check_bullet_quality("x" * 181)
    passive = check_bullet_quality("Reports were generated by the team weekly")
    quantified = check_bullet_quality("Increased revenue by 25% across 3 regions")

    assert {warning.code for warning in weak} >= {"weak_opener", "no_quantification"}
    assert any(warning.code == "too_long" for warning in long_text)
    assert any(warning.code == "passive_voice" for warning in passive)
    assert quantified == []


def test_action_verbs_only_for_weak_openers():
    assert action_verb_suggestions("Responsible for platform work")
    assert not action_verb_suggestions("Shipped 3 major releases")


@pytest.mark.parametrize(
    ("opener", "verb", "expected"),
    [
        ("Responsible for", "Delivered", "Delivered platform work"),
        ("Helped with", "Built", "Built onboarding"),
        ("Worked on", "Launched", "Launched billing"),
        ("Duties included", "Streamlined", "Streamlined intake"),
        ("Assisted in", "Guided", "Guided rollout"),
    ],
)
def test_replace_weak_opener_variants(opener: str, verb: str, expected: str):
    assert replace_weak_opener(f"{opener} platform work", verb).startswith(verb)


@pytest.mark.django_db
def test_completeness_score_empty_profile():
    profile = Profile.objects.create(session_key="empty")
    result = completeness_score(profile)

    assert result.score < 20
    assert all(
        not passed for label, _points, passed in result.breakdown if label != "No flagged bullets"
    )


@pytest.mark.django_db
def test_completeness_flags_incomplete_bullets(profile):
    experience = profile.experiences.first()
    assert experience is not None
    Achievement.objects.create(experience=experience, text="Responsible for legacy systems", order=3)

    result = completeness_score(profile)

    assert any(label == "No flagged bullets" and not passed for label, _points, passed in result.breakdown)


def test_short_keyword_does_not_match_inside_other_tokens():
    resume_tokens = tokenize_for_matching("Senior Django engineer building APIs")

    assert not keyword_present_in_resume("go", resume_tokens)
    assert keyword_present_in_resume("django", resume_tokens)


@pytest.mark.django_db
def test_keyword_analysis_partitions_present_and_missing(profile):
    analysis = analyze_job_description(
        profile,
        "Rust Kubernetes quantum computing blockchain",
    )

    assert analysis.present == []
    assert analysis.missing
    assert analysis.match_percentage == 0


def test_extract_keywords_ranks_terms():
    keywords = extract_keywords(
        "Python python Django django automation automation reporting reporting",
        top_n=5,
    )

    assert keywords
    assert keywords[0] in {"python", "django", "automation", "reporting"}


@pytest.mark.django_db
def test_profile_resume_text_includes_certifications(profile):
    text = profile_resume_text(profile).lower()

    assert "aws solutions architect" in text
    assert Certification.objects.filter(profile=profile).exists()
